// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgayxhdhxizmpnxtcnwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYXl4aGRoeGl6bXBueHRjbnd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDQ1NTksImV4cCI6MjA3MzYyMDU1OX0.6g3nlVmltJoWE-tQuudnkEGiZVMD2WZGZ1GSnURVwXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});